
const menuList = [
    {
        title:'用户管理',
        icon:'user',
        path:'/home'
    },
    {
        title:'公告管理',
        icon:'form',
        path:'/announcement'
    },
    {
        title:'订单管理',
        icon:'table',
        path:'/order',
        children:[
            {
                title:'待审核订单',
                icon:'xxx',
                path:'/unaudited',
            },
            {
                title:'已审核订单',
                icon:'xxx',
                path:'/audited',
            }
        ]
    },
    {
        title:'网站管理',
        icon:'container',
        path:'/webSet',
        children:[
            {
                title:'待审核网站',
                icon:'xxx',
                path:'/unauditedWeb',
            },
            {
                title:'已审核网站',
                icon:'xxx',
                path:'/auditedWeb',
            }
        ]
    },
    {
        title:'设置',
        icon:'check-circle',
        path:'/set',
        children:[
            {
                title:'分类设置',
                icon:'xxx',
                path:'/sortSet',
            },
            {
                title:'代理费设置',
                icon:'xxx',
                path:'/systemSet',
            }
        ]
    }
];
export default menuList